### ISSUE TITLE
Errata

### ISSUE THREAD

**Issue by ernest-czol** [katonaaron/kotlinise-your-android#1]
https://github.com/katonaaron/kotlinise-your-android/blob/651f91c49cfe799c755e2d3305021247d2a983b4/exercises/Exercises%201/src/Exercise%205.kts#L44

I think the correct version which handles properly negative, 0, 1 is:
fun Int.isPrime() = this > 1 && (2..this / 2).none { it % 2 == 0 }

**Comment by katonaaron** [comment]
Thank you. I added  `this > 1 &&`  to the function. The [commit](https://github.com/katonaaron/kotlinise-your-android/commit/e7ad99a970015fa0e0749877dcfa12d4e74cd067)
